workflows:
  # Android 构建
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages pub get
      - name: Build Android APK
        script: |
          cd mobile
          flutter build apk --release
      - name: Build Android App Bundle
        script: |
          cd mobile
          flutter build appbundle --release
    artifacts:
      - mobile/build/app/outputs/**/*.apk
      - mobile/build/app/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com

  # iOS 构建
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd mobile/ios
          pod install
      - name: Build iOS
        script: |
          cd mobile
          flutter build ios --release --no-codesign
    artifacts:
      - mobile/build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
